services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    restart: "no" # cámbialo a unless-stopped si quieres que arranque solo

volumes:
  postgres_data:
